### PR TITLE
Use Better Crafting's API to add compatibility

### PR DESCRIPTION
**Pull request by KhloeLeclair**
Hello there!

This adds support for Better Crafting by using Better Crafting's API to teach it how to handle Item Bags, and tell it about any relevant Item Bags in the player's inventory + existing inventories. Once I saw you had implemented a basic IInventory, I wanted to do this.

Please let me know what you think. I'd like to get support for Item Bags + Better Crafting since a lot of users have asked for it over time, and I think it'd be best implemented with something like this.

You might want to clean it up a bit, but I based the logic on what you're doing for the vanilla crafting menu.

### CODE REVIEW

**Comment by Videogamers0** [comment]
Very nice, I'm sure a lot of users will love this feature. The code looks good. I'll try testing it tomorrow evening when I get a chance. The `ItemBagCraftingInventory` is a very minimal implementation of `IInventory` -  a lot of the interface methods are not implemented at all since it was only intended to be used for removing items from bags during crafting actions. So hopefully the unimplemented methods won't cause any issues down the road.

**Comment by Videogamers0** [comment]
Hmm there's definitely 1 or 2 bugs I'm having trouble pinpointing. In my save file, I have a Massive Rucksack with a very large amount of wood in it (at least a few thousand). If I open the crafting menu, then right-click a recipe that requires wood (such as 'Gate', (10 wood)), and set it to batch-craft a large quantity such as 100, it's only crafting 20. The Better Crafting menu tooltip reports the correct amount of wood after crafting those 20 gates, but if I close the crafting menu and then open my rucksack from the inventory, no wood was actually consumed. It seems like the rucksack's wood corrects itself the next time the crafting menu is opened.

**Comment by Videogamers0** [comment]
It looks like the same bug is happening if I close the crafting menu by clicking the X button in the top-right corner, rather than closing the crafting menu by pressing E.

This set of steps causes incorrect output:
1. Open game menu by pressing E
2. Switch to crafting tab
3. Craft a gate via left-click
4. Click X in top-right corner to close game menu
5. Open game menu by pressing E
6. Open rucksack
7. No wood was consumed

This set of steps works correctly:
1. Open game menu by pressing E
2. Switch to crafting tab
3. Craft a gate via left-click
4. Close game menu by pressing E, rather than clicking the X in top-right
5. Open game menu by pressing E
6. Open rucksack
7. The wood was correctly consumed

The issue also seems to occur if I switch tabs in the game menu without actually closing it:
1. Open game menu by pressing E
2. Switch to crafting tab
3. Craft a gate via left-click
4. Switch to inventory tab (do not press E, do not click the X in top-right. So keep the game menu open but just switch tabs)
5. Open rucksack
6. No wood was consumed

**Comment by Videogamers0** [comment]
In [CraftingHandler.cs](https://github.com/Videogamers0/SDV-ItemBags/blob/master/ItemBags/CraftingHandler.cs), `ItemBagCraftingInventory.Close()` is intentionally invoked anytime the user leaves the crafting menu since item stacks may have had to be split up into several chunks. For example, if your rucksack contained 1015 wood, then it would have to temporarily split it into 2 stacks, 1 with 999, and 1 with 16 wood, because the vanilla game code has logic that caps the Stack amount at 999 which causes problems when the stack size is being reduced. (I.E., if you had a single stack of 1015, and it consumed 10, instead of going to 1005, it would get capped down to 999 the moment that property value was modified.)

`ItemBagCraftingInventory.Close()` is invoked when the `StardewValley.Menus.GameMenu` is closed (which is tracked via `Helper.Events.Display.MenuChanged`) OR also when the active tab within the `GameMenu` is changed (this was a bit annoying to detect so I had to poll for changes to `GameMenu.currentTab`  on every game tick).

So I think the bugs described above are related to the `ItemBagCraftingInventory.Close()` logic not being invoked when necessary.

Though I guess that still doesn't explain why the batch-crafting menu was capping me at 20 gates when I tried to make 100.

**Comment by KhloeLeclair** [comment]
So, the "capped at 20" thing was an unrelated bug in Better Crafting. That's fixed now in 2.13.0.

Additionally, I've introduced a new API to add events when BC wants exclusive access to an inventory for writing + when it's done, so now we can use that end event to perform bag re-sync. This should be more reliable.

**Pull request merged**
